//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceStockUpdateCrawler.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasterProduct
    {
        public long ID { get; set; }
        public string SKU { get; set; }
        public Nullable<long> BrandID { get; set; }
        public string BrandName { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<long> SubCategoryID { get; set; }
        public string SubCategoryName { get; set; }
        public string ProductName { get; set; }
        public string SearchTags { get; set; }
        public string SingleLineSearch { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public string ThumbnailURL { get; set; }
        public string ImageURL { get; set; }
        public string Description { get; set; }
        public string Sellers { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Highlights { get; set; }
    }
}
